spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB_NAME:hero_book}?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    jpa:
      show-sql: true
