server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB_NAME:hero_book}?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    table: auth_flyway_schema_history
    baseline-on-migrate: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
